name: ecotrack_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  wifi_iot: ^0.3.19+2
  wifi_scan: ^0.4.1+2
  connectivity_plus: ^4.0.1
  flutter_dotenv: ^5.2.1
  network_info_plus: ^6.1.4
  cached_network_image: ^3.4.1
  fl_chart: ^1.0.0
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  image_picker: ^1.1.2
  syncfusion_flutter_charts: ^29.1.38
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  package_info_plus: ^8.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
        - asset: assets/fonts/arial_bold.ttf
          weight: 700

    - family: Gotham
      fonts:
        - asset: assets/fonts/gotham_light.otf
          weight: 300
        - asset: assets/fonts/gotham_medium.otf
          weight: 500
        - asset: assets/fonts/gotham_book.otf
          weight: 400
        - asset: assets/fonts/gotham_bold.otf
          weight: 700

    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova_light.otf
          weight: 300
        - asset: assets/fonts/proximanova_regular.ttf
          weight: 400
        - asset: assets/fonts/proximanova_bold.otf
          weight: 700
        - asset: assets/fonts/proximanova_extrabold.otf
          weight: 800
        - asset: assets/fonts/proximanova_black.otf
          weight: 900

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/navbarlogos/
    - assets/icons/appliancelogos/
    - assets/icons/appliancelogos/aircon/
    - assets/icons/appliancelogos/computer/
    - assets/icons/appliancelogos/default/
    - assets/icons/appliancelogos/fan/
    - assets/icons/appliancelogos/laptop/
    - assets/icons/appliancelogos/microwave/
    - assets/icons/appliancelogos/refrigerator/
    - assets/icons/appliancelogos/smartphone/
    - assets/icons/appliancelogos/tv/
    - assets/icons/appliancelogos/washing_machine/
    - assets/lottie/
    - .env
